### ISSUE TITLE
Runs out of memory with a large number of votes.

### ISSUE THREAD

**Issue by LiamM32** [LiamM32/Eurovision_Condorcet#1]
This program runs out of memory when the number of votes is too large. Here is the output when using a .cvotes file with millions of votes.
`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /home/liam/src/Eurovision_Condorcet/vendor/julien-boudry/condorcet/src/Algo/Pairwise.php on line 206`

**Comment by julien-boudry** [comment]
Try to update your PHP memory limit in the .ini setting file.

Alternatively, you can set it at the beginning of your main file:
```php
ini_set('memory_limit', '8192M'); # Or more!
```

If that's not enough, then more sophisticated => https://www.condorcet.io/3.AsPhpLibrary/8.GoFurther/5.GetStartedToHandleMillionsOfVotes (but you will need the PDO Sqlite extension)

**Comment by julien-boudry** [comment]
Another and smarter way, i to use VoteWeight instead.

```yaml
#/Candidates: FIN; SWE; NOR; UKR; ISR; ITA; HRV; POL; MDA; ALB; CYP; BEL; ARM; FRA; LTU; SVN; CZE; CHE; EST; AUS; AUT; PRT; SRB; DEU; GBR; ESP
#/Implicit Ranking: true
#/Weight allowed: true

FRA || ARM > ISR > MDA > ITA > FIN > PRT > UKR > SWE > BEL > NOR ^415145
```

It's just 415145 time faster (ingestion and pairwise computation, not method calculation) and uses 415145 less memory.

But your method **must** manage the weight. For pairwise based method, it's easy: the pairwise of the internal API has already done it for you.

The perfect method to do it instead of `countVote` is `sumValidVotesWeightWithConstraints`. It manages weight, but also constraint (you don't use any, but some others could want to).

**Comment by LiamM32** [comment]
Sure. It would get the same result in this exact case. But the reason why I used quantities instead of weights is to test how well it will work when there are numerous combinations of votes, as would be the case in the real world. Perhaps if it were used in the real world, there could be a script that would combine any identical votes together into a single vote with a weight of multiple. But given the large number of possible combinations, [which is](https://oeis.org/A000670/list) 2677687796244384203115 for 20 candidates, and this is supposed to handle 26, I suspect such a script would take more computing time than it would save.

Does `sumValidVotesWeightWithConstraints` have any additional benefits over `countVote` other than weight and constraints?

**Comment by julien-boudry** [comment]
> Does `sumValidVotesWeightWithConstraints` have any additional benefits over `countVote` other than weight and constraints?

It's compliant with all API and logic. Can be slower on large lection, but we should no be significant.
