### ISSUE TITLE
Allow group balance to be stated in the .cvotes file

### ISSUE THREAD

**Issue by LiamM32** [LiamM32/Eurovision_Condorcet#15]
I may make a derived class of `CondorcetElectionFormat`, and add the ability to process group balance from the .cvotes file itself. My biggest barrier so far is that I would need to figure out how to write a regular expression for the format I want. I want it to be written like the following:
`#/Group balance: Public=50; Jury=0.25; Jury2=0.25`

I may also have other parameters to be set in the cvotes file.

**Comment by julien-boudry** [comment]
I'm not sure that this actual class, this actual parser, is very well designed to be extended.
Probably I made something effective and linear (memory performance in case of big file), but not really modular / extendable because it has a strong couple with the Condorcet library ecosystem.

Maybe code could be refactored to be more easily extendable, at least for parameters parsing. But maybe it could be easier to write a new and agnostic parser, less (or not) coupled with Condorcet library.

**Comment by julien-boudry** [comment]
Best effort could be writing a regular expression, as a last statement, searching and parsing this line on the whole file.
Could work if the file is not too big (98% of use cases are safe), or will fail cause of the memory limit, with some CPU boost.

**Comment by LiamM32** [comment]
I thought I would just copy and paste `CondorcetElectionFormat::readParameters()` and `CondorcetElectionFormat::setDataToAnElection()`.

I attempted this, and it seemed like it was going to work, but the problem was that I needed to set a variable in `Contest` that isn't in `Election`. Here's the error I got:
```
PHP Fatal error:  Declaration of EurovisionVoting\EurovisionCondorcetFormat::setDataToAnElection(EurovisionVoting\Contest $contest = <expression>, ?Closure $callBack = null): EurovisionVoting\Contest must be compatible with CondorcetPHP\Condorcet\Tools\Converters\CondorcetElectionFormat::setDataToAnElection(CondorcetPHP\Condorcet\Election $election = <expression>, ?Closure $callBack = null): CondorcetPHP\Condorcet\Election in /home/liam/src/Eurovision_Condorcet/src/EurovisionCondorcetFormat.php on line 18
```
Yeah; Now I see what you mean when you said it wasn't designed to be extendable.

**Comment by julien-boudry** [comment]
Should be caused by the interface. try to rename `$contest` variable to `$election`.

If you give me some time, I can refactor the parameters reading in a more agnostic way. Then you will not need anymore to extend `CondorcetElectionFormat::readParameters()` or write regex.

**Comment by LiamM32** [comment]
Alright. You can see I added a function to the `Init` class in the latest commit. This imitates what happens in `CondorcetElectionFormat::readParameters()`. It's not a very clean solution, but it's working.

But I realized that the regular expressions you used don't capture each entry on the list individually in one step. It would probably be possible to put each candidate as a separate array entry in one step, but that goes beyond my knowledge in regular expressions.

**Comment by julien-boudry** [comment]
> But I realized that the regular expressions you used don't capture each entry on the list individually in one step. It would probably be possible to put each candidate as a separate array entry in one step, but that goes beyond my knowledge in regular expressions.

Yes, it's not really optimal. Working very well, but focused [on the actual spec.](https://github.com/CondorcetVote/CondorcetElectionFormat), without considering the free extensions. Because this class is inside the Condorcet project, if I'd had the ambition to make it a real independent parser, I'd have set up an independent library to do it. *

_* (Maybe, one day, I will do it in Rust, to learn it!)_

**Comment by julien-boudry** [comment]
I will refactor the parameters parsing soon. Maybe before the v4.5 release, maybe for the next one.

Will provide an array inside a property, containing parameters in an agnostic way.

**Comment by julien-boudry** [comment]
The last two commits inside dev-4.5 branch add support for raw parameters parsing.

The new property is `$CondorcetElectionFormat->parameters`, it's an array indexed by parameters name as keys, and values are always a string. Parameters and values are trimmed but it's the only transformation.
You can read a very subtle test here (with a lot of traps): https://github.com/julien-boudry/Condorcet/blob/85c198d4a03fa73bc581a6a63f7923e7ebb7ba60/Tests/src/Tools/Converters/CEF/CondorcetElectionFormatTest.php

**Comment by LiamM32** [comment]
So I should now just modify `CondorcetElectionFormat::readParameters()`?

**Comment by julien-boudry** [comment]
You have nothing to modify. Juste use the native class and read the property `parameters`

**Comment by LiamM32** [comment]
I didn't do this exactly, as I thought it looked cleaner with an inherited class. You can see how I did it. It's merged to master now.
