### ISSUE TITLE
`Call to undefined method CondorcetPHP\Condorcet\Election::getPopulations()`

### ISSUE THREAD

**Issue by LiamM32** [LiamM32/Eurovision_Condorcet#2]
Currently, if there are no other errors, running this program results in the following error:
```
PHP Fatal error:  Uncaught Error: Call to undefined method CondorcetPHP\Condorcet\Election::getPopulations() in /home/liam/src/Eurovision_Condorcet/src/main.php:18
Stack trace:
#0 {main}
  thrown in /home/liam/src/Eurovision_Condorcet/src/main.php on line 18
```
It is not clear to me why this error happens.
@julien-boudry

**Comment by julien-boudry** [comment]
Try:

```php
$contest = new Contest;
$contest = $votesdata->setDataToAnElection($contest);
$contest->getPopulations();
```

Because if you call `setDataToAnElection` without argument, create and return a new Election object.

**Comment by LiamM32** [comment]
Thank you. This works. In the most recent commit this program doesn't have any errors.
