### ISSUE TITLE
Incorrect vote counts for each tag/country

### ISSUE THREAD

**Issue by LiamM32** [LiamM32/Eurovision_Condorcet#4]
The _Contest::countVotersByCountry()_ function is supposed to count the number of votes coming from each country. Each vote is supposed to have a 3-letter country code as a tag. But when used with the included _some-votes.cvotes_ file, it only counts the first set of identical votes listed for each country. But every country should have two sets of votes.

For example, here are the votes from Albania, as written as lines in _some-votes.cvotes_:
```
ALB || ITA > SWE > HRV > CYP > FIN > ISR > NOR > FRA > SVN > POL *19
ALB || SWE > ARM > EST > EST > CHE > ISR > ISR > BEL > CYP > CYP *10
```
So Albania should have given 29 votes in total. But only 19 are counted in this function. I have not yet determined if the second set of votes are ignored entirely throughout the process.

**Comment by julien-boudry** [comment]
Your set of the vote, on the second part, seems to be wrong, candidates are duplicated on the same vote.
ALB || SWE > ARM > **EST > EST** > CHE > **ISR > ISR** > BEL > **CYP > CYP** *10

Currently, CondorcetElectionFormat readers just ignore badly formatted votes, without any warning.
Maybe more options (to throw something) can be added for the next version.

**Comment by LiamM32** [comment]
Thank you for pointing this out. I used Libreoffice Calc to generate these votes based on some existing data. It was a problem with how I copied & pasted things into libreoffice that caused this to happen.
